/**
 * Compiles "CoachRx Updates.dc.html" into THREE pages.
 *
 * The design file carries one section per route — Route /roadmap, Route /changelog and
 * Route /feature-requests — so all three tab states preview together in Claude Design. The
 * compiler has no concept of that: left alone it emits every section into one page, so /roadmap
 * would render all three tabs stacked on top of each other.
 *
 * This compiles the file once, then splits the result by `data-screen-label="Route /x"` and writes
 * one module per route. Live roadmap rows are injected the same way build-roadmap.mjs does it.
 *
 * Outputs src/generated/updates-roadmap.ts, updates-changelog.ts, updates-requests.ts
 */
import fs from "node:fs";
import path from "node:path";
import * as cheerio from "cheerio";
import { compileDesign } from "./dc-compile.mjs";

const ROOT = process.cwd();
const DROOT = path.join(ROOT, "design");
const GEN = path.join(ROOT, "src", "generated");

const findDesign = (f) => {
  const d = path.join(DROOT, f);
  if (fs.existsSync(d)) return d;
  for (const e of fs.readdirSync(DROOT, { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    const n = path.join(DROOT, e.name, f);
    if (fs.existsSync(n)) return n;
  }
  return d;
};

const SRC = findDesign("CoachRx Updates.dc.html");
if (!fs.existsSync(SRC)) {
  console.log("\nbuild-updates:\n  skip (design/CoachRx Updates.dc.html not built yet)");
  process.exit(0);
}

const ROUTES = [
  { label: "Route /roadmap", name: "updates-roadmap", route: "/roadmap" },
  { label: "Route /changelog", name: "updates-changelog", route: "/changelog" },
  { label: "Route /feature-requests", name: "updates-requests", route: "/feature-requests" },
];

// Live roadmap rows, if fetch-roadmap has run. Falls back to the design's sample data.
const DATA = path.join(ROOT, "src", "data", "roadmap.json");
let override;
if (fs.existsSync(DATA)) {
  const d = JSON.parse(fs.readFileSync(DATA, "utf8"));
  const rows = (d.items || d.rows || []).filter((r) => r.publicRoadmap !== false);
  const pick = (status) =>
    rows
      .filter((r) => (r.status || "").toLowerCase().includes(status))
      .map((r) => ({ feature: r.feature || r.name, pillar: r.pillar || "", summary: r.summary || "" }));
  const building = pick("building");
  const upnext = pick("up next");
  if (building.length || upnext.length) {
    override = {
      building,
      upnext,
      buildingCount: building.length,
      upnextCount: upnext.length,
      updated: new Date()
        .toLocaleDateString("en-US", { month: "short", year: "numeric" })
        .toUpperCase(),
    };
  }
}

const out = compileDesign(SRC, override);
const $ = cheerio.load(out.html, null, false);

const all = $("section").filter((_, e) => /^Route \//.test($(e).attr("data-screen-label") || ""));
if (all.length !== ROUTES.length) {
  console.error(
    `build-updates: expected ${ROUTES.length} route sections, found ${all.length}.\n` +
      `  The design file must carry one <section data-screen-label="Route /x"> per tab.\n` +
      `  Found: ${all.map((_, e) => $(e).attr("data-screen-label")).get().join(", ") || "none"}`,
  );
  process.exit(1);
}

fs.mkdirSync(GEN, { recursive: true });
console.log("\nbuild-updates:");

for (const r of ROUTES) {
  const $$ = cheerio.load(out.html, null, false);
  // keep this route's section, drop the other two, and strip the preview label bars
  $$("section").each((_, e) => {
    const label = $$(e).attr("data-screen-label") || "";
    if (/^Route \//.test(label) && label !== r.label) $$(e).remove();
  });
  $$("[class*='crx-route']").remove();
  $$("*")
    .filter((_, e) => /^Build preview · direct route/.test(($$(e).text() || "").trim()))
    .remove();

  const html = ($$.root().html() || "").trim();
  fs.writeFileSync(
    path.join(GEN, `${r.name}.ts`),
    `// GENERATED by scripts/build-updates.mjs from "CoachRx Updates.dc.html" (${r.route}).\n` +
      `// Do not edit by hand.\n` +
      `export const html = ${JSON.stringify(html)};\n` +
      `export const css = ${JSON.stringify(out.css)};\n` +
      `export const script = ${JSON.stringify(out.script)};\n`,
  );
  console.log(`  ok   ${r.name.padEnd(20)} ${String(Math.round(html.length / 1024)).padStart(4)}KB  ${r.route}`);
}
