/**
 * Compiles the three blog design templates with REAL post data.
 *
 * The design files ship with sample articles so they preview correctly in Claude
 * Design. This script replaces that sample data with the actual 340 posts, then hands
 * the compiled HTML to the Next pages. The design markup, CSS and behaviour are
 * untouched — only the data changes.
 *
 * Outputs into src/generated/:
 *   blog-index.ts          one page, all posts as rows
 *   topic-<slug>.ts        one per topic archive (9)
 *   blog-post.ts           the post template, with @@token@@ placeholders that
 *                          src/app/articles/[slug]/page.tsx substitutes per post
 *   blog-manifest.ts       maps topic slug -> module name
 *
 * Run via `npm run dc:blog`, and automatically as part of `prebuild`.
 */
import fs from "node:fs";
import path from "node:path";
import * as cheerio from "cheerio";
import { compileDesign } from "./dc-compile.mjs";

const ROOT = process.cwd();
const SRC = path.join(ROOT, "design");
const OUT = path.join(ROOT, "src", "generated");
const POSTS = JSON.parse(fs.readFileSync(path.join(ROOT, "src", "data", "posts.json"), "utf8"));

// Topics, kept in sync with src/data/topics.ts by reading it rather than duplicating.
const topicsSrc = fs.readFileSync(path.join(ROOT, "src", "data", "topics.ts"), "utf8");
const TOPICS = [...topicsSrc.matchAll(/tag:\s*"([^"]+)",\s*slug:\s*"([^"]+)",\s*title:\s*"([^"]+)",\s*intro:\s*\n?\s*"((?:[^"\\]|\\.)*)"/g)]
  .map((m) => ({ tag: m[1], slug: m[2], title: m[3], intro: m[4].replace(/\\"/g, '"') }));

if (!TOPICS.length) {
  console.error("build-blog: could not parse topics from src/data/topics.ts");
  process.exit(1);
}

const fmtDate = (d) =>
  new Date(d).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

/** Two-letter mono initials the design shows in the left rail. */
const initials = (tag) =>
  tag.split(/\s+/).filter((w) => /^[A-Za-z]/.test(w)).slice(0, 2).map((w) => w[0]).join("").toUpperCase() || "CR";

const toRow = (p) => ({
  tag: p.primaryTag,
  title: p.title,
  desc: p.description,
  date: fmtDate(p.date),
  initials: initials(p.primaryTag),
  href: `/articles/${p.slug}`,
  img: p.featuredImage || "",
  alt: p.featuredImageAlt || "",
});

const chipsFor = (activeSlug) => [
  { label: "All", href: "/articles", cls: activeSlug ? "" : "is-active" },
  ...TOPICS.map((t) => ({ label: t.title, href: `/topics/${t.slug}`, cls: t.slug === activeSlug ? "is-active" : "" })),
];

const write = (name, out, extra = "") => {
  fs.writeFileSync(
    path.join(OUT, `${name}.ts`),
    `// GENERATED by scripts/build-blog.mjs. Do not edit by hand.\n` +
      `export const html = ${JSON.stringify(out.html)};\n` +
      `export const css = ${JSON.stringify(out.css)};\n` +
      `export const script = ${JSON.stringify(out.script)};\n` +
      extra
  );
  return { kb: Math.round(out.html.length / 1024), unresolved: out.unresolved };
};

const problems = [];
const check = (label, out) => {
  const leftover = (out.html.match(/\{\{/g) || []).length;
  const directives = (out.html.match(/<sc-(for|if)/g) || []).length;
  if (leftover || directives) problems.push(`${label}: ${leftover} braces, ${directives} directives`);
  if (out.unresolved.length) problems.push(`${label}: unresolved ${out.unresolved.slice(0, 4).join(", ")}`);
};

fs.mkdirSync(OUT, { recursive: true });
console.log("\nbuild-blog:");

/* ------------------------------------------------------------------ blog index */
{
  const rows = POSTS.map(toRow);
  const out = compileDesign(path.join(SRC, "CoachRx Blog Index.dc.html"), (d) => ({
    ...d,
    chips: chipsFor(null),
    // Two "start here" posts, then every remaining article as a row. All 340 links are
    // in the HTML rather than behind a load-more, so the whole library is crawlable.
    featured: rows.slice(0, 2),
    visible: rows.slice(2),
    showFeatured: true,
    isEmpty: false,
    isSparse: false,
    hasMore: false,
    activeTag: "",
    countLabel: `${POSTS.length} articles`,
  }));
  check("blog-index", out);
  const r = write("blog-index", out);
  console.log(`  ok   blog-index      ${String(r.kb).padStart(4)}KB   ${POSTS.length} posts`);
}

/* --------------------------------------------------------------- topic archives */
{
  const manifest = [];
  for (const t of TOPICS) {
    const posts = POSTS.filter((p) => p.primaryTag === t.tag || (p.tags || []).includes(t.tag));
    const rows = posts.map(toRow);
    const out = compileDesign(path.join(SRC, "CoachRx Tag Archive.dc.html"), (d) => ({
      ...d,
      tagName: t.title,
      intro: t.intro,
      countLabel: `${posts.length} article${posts.length === 1 ? "" : "s"}`,
      shownLabel: "",
      chips: chipsFor(t.slug),
      visible: rows,
      isEmpty: posts.length === 0,
      // Below eight posts the design switches to a wider, sparser layout so a short
      // archive reads as deliberate rather than broken.
      isSparse: posts.length < 8,
      hasMore: false,
      siblings: TOPICS.filter((x) => x.slug !== t.slug).slice(0, 4).map((x) => ({ label: x.title, href: `/topics/${x.slug}` })),
    }));
    check(`topic-${t.slug}`, out);
    const r = write(`topic-${t.slug}`, out);
    manifest.push({ slug: t.slug, module: `topic-${t.slug}`, title: t.title, count: posts.length });
    console.log(`  ok   topic-${t.slug.padEnd(28)} ${String(r.kb).padStart(4)}KB   ${String(posts.length).padStart(3)} posts`);
  }
  const imports = manifest.map((m, i) => `import * as t${i} from "./${m.module}";`).join("\n");
  const entries = manifest.map((m, i) => `  "${m.slug}": t${i},`).join("\n");
  fs.writeFileSync(
    path.join(OUT, "topic-pages.ts"),
    `// GENERATED by scripts/build-blog.mjs. Do not edit by hand.\n${imports}\n\n` +
      `export const TOPIC_PAGES: Record<string, { html: string; css: string; script: string }> = {\n${entries}\n};\n`
  );
  fs.writeFileSync(
    path.join(OUT, "blog-manifest.ts"),
    `// GENERATED by scripts/build-blog.mjs. Do not edit by hand.\n` +
      `export const TOPIC_PAGES = ${JSON.stringify(manifest, null, 1)} as const;\n`
  );
}

/* ------------------------------------------------------------------- post detail */
{
  // The post template is compiled once with tokens, then substituted per post at
  // render time. 340 separate compiled pages would bloat the bundle for no gain.
  const T = (k) => `@@${k}@@`;
  const out = compileDesign(path.join(SRC, "CoachRx Blog Post.dc.html"), (d) => ({
    ...d,
    post: {
      tag: T("tag"), tagHref: T("tagHref"), title: T("title"), author: T("author"),
      date: T("date"), readingTime: T("readingTime"), lede: T("lede"),
      img: T("img"), alt: T("alt"),
    },
    author: {
      name: T("authorName"), role: T("authorRole"), bio: T("authorBio"),
      avatar: "", initials: T("authorInitials"),
    },
    related: [0, 1, 2].map((i) => ({
      tag: T(`rel${i}Tag`), title: T(`rel${i}Title`), date: T(`rel${i}Date`),
      initials: T(`rel${i}Initials`), href: T(`rel${i}Href`),
    })),
  }));
  check("blog-post", out);
  // Swap the design's sample article for one token. Doing it here with a parser is
  // robust; doing it in the page with a regex would break on the first nested div.
  const $p = cheerio.load(out.html, null, false);
  const $body = $p('[data-slot="body"]');
  if ($body.length) $body.html("@@BODY@@");
  out.html = $p.html();
  const bodyMarker = /@@BODY@@/.test(out.html);
  if (!bodyMarker) problems.push('blog-post: data-slot="body" not found, cannot inject article HTML');
  const tokens = [...new Set((out.html.match(/@@[a-zA-Z0-9]+@@/g) || []))];
  const r = write("blog-post", out, `export const tokens = ${JSON.stringify(tokens)} as const;\n`);
  console.log(`  ok   blog-post       ${String(r.kb).padStart(4)}KB   ${tokens.length} tokens, body slot ${bodyMarker ? "ready" : "MISSING"}`);
}

if (problems.length) {
  console.error("\nbuild-blog problems:");
  for (const p of problems) console.error("  ! " + p);
  process.exit(1);
}
console.log("build-blog: complete\n");
