/**
 * Compiles "CoachRx Roadmap.dc.html" against the real Feature Hub rows.
 *
 * Same pattern as build-blog.mjs: the design file ships with sample cards so it previews
 * correctly in Claude Design, and this replaces that sample data with what came out of
 * Notion. The design markup, CSS and behaviour are untouched — only the data changes.
 *
 * Skips cleanly if the design file does not exist yet, so this can sit in `prebuild` before
 * the design is built without breaking anything.
 *
 * Outputs src/generated/roadmap.ts
 */
import fs from "node:fs";
import path from "node:path";
import { compileDesign } from "./dc-compile.mjs";

const ROOT = process.cwd();
const DROOT = path.join(ROOT, "design");
const findDesign = (f) => {
  const d = path.join(DROOT, f);
  if (fs.existsSync(d)) return d;
  for (const e of fs.readdirSync(DROOT, { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    const n = path.join(DROOT, e.name, f);
    if (fs.existsSync(n)) return n;
  }
  return d;
};
const SRC = findDesign("CoachRx Roadmap.dc.html");
const DATA = path.join(ROOT, "src", "data", "roadmap.json");
const OUT = path.join(ROOT, "src", "generated", "roadmap.ts");

if (!fs.existsSync(SRC)) {
  console.log("\nbuild-roadmap:\n  skip (design/CoachRx Roadmap.dc.html not built yet)");
  process.exit(0);
}
if (!fs.existsSync(DATA)) {
  console.log("\nbuild-roadmap:\n  skip (src/data/roadmap.json missing, run fetch-roadmap first)");
  process.exit(0);
}

const data = JSON.parse(fs.readFileSync(DATA, "utf8"));

const fmtMonth = (d) =>
  d ? new Date(d).toLocaleDateString("en-US", { month: "short", year: "numeric" }).toUpperCase() : "";

/** Platform badges, uppercased here rather than with text-transform so they can be measured. */
const badges = (arr) => (arr || []).map((p) => p.toUpperCase());

const card = (r) => ({
  feature: r.feature,
  summary: r.summary,
  pillar: (r.pillar || "").toUpperCase(),
  platform: badges(r.platform),
  // A single string is easier for the design to render than a nested loop.
  platformLabel: badges(r.platform).join(" · "),
  // Used by the platform filter: a space-joined class list the runtime can match on.
  platformCls: (r.platform || []).map((p) => "p-" + p.toLowerCase().replace(/\s+/g, "-")).join(" "),
});

const columns = (data.columns || []).map((c) => ({
  status: c.status,
  label: (c.label || "").toUpperCase(),
  count: c.items.length,
  isEmpty: c.items.length === 0,
  items: c.items.map(card),
}));

const shipped = (data.shipped || []).map((r) => ({ ...card(r), month: fmtMonth(r.released) }));

const out = compileDesign(SRC, (d) => ({
  ...d,
  columns,
  shipped,
  hasShipped: shipped.length > 0,
  updated: fmtMonth(data.generatedAt) || "",
  updatedFull: data.generatedAt || "",
  totalCount: columns.reduce((n, c) => n + c.count, 0),
}));

const leftover = (out.html.match(/\{\{/g) || []).length;
const directives = (out.html.match(/<sc-(for|if)/g) || []).length;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/build-roadmap.mjs. Do not edit by hand.\n` +
    `export const html = ${JSON.stringify(out.html)};\n` +
    `export const css = ${JSON.stringify(out.css)};\n` +
    `export const script = ${JSON.stringify(out.script)};\n`
);

console.log("\nbuild-roadmap:");
console.log(
  `  ok   roadmap    ${String(Math.round(out.html.length / 1024)).padStart(4)}KB   ` +
    columns.map((c) => `${c.label} ${c.count}`).join(", ") +
    `, shipped ${shipped.length}`
);
if (leftover || directives) console.log(`  !!   ${leftover} braces, ${directives} directives left`);
if (out.unresolved.length) console.log(`  !!   unresolved: ${out.unresolved.slice(0, 6).join(", ")}`);
